[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0

[program:dogecoind]
command=/sbin/su-exec dogecoin:dogecoin /usr/local/bin/dogecoind -datadir=/dogecoin -conf=/config/dogecoin.conf -daemon=0 -printtoconsole
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:cloudflared]
command=/usr/local/bin/cloudflared tunnel --no-autoupdate run --token-file /config/cloudflared/token
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
